name: sarang_trucks
description: "Professional yuk mashinalari ijarasi - Sarang Trucks"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Backend & Database
  supabase_flutter: ^2.0.0

  # State Management
  provider: ^6.1.0

  # UI & UX
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Storage & Preferences
  shared_preferences: ^2.2.0

  # External Services
  url_launcher: ^6.2.0

  # Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
